name = "app-notification-server"
main = "index.js"
compatibility_date = "2023-10-30"

# KHAI BÁO KV NAMESPACE
# Để chạy được, bạn cần chạy lệnh: wrangler kv:namespace create NOTIFICATIONS
# Sau đó copy id sinh ra và dán vào dưới đây:
[[kv_namespaces]]
binding = "NOTIFICATIONS"
id = "thay_id_cua_ban_vao_day"
